// https://meyerweb.com/eric/tools/css/reset/

import { CSSObject } from "@emotion/react";

export const resetStyles: CSSObject = {
	html: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	body: { lineHeight: "1" },
	div: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	span: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	applet: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	object: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	iframe: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	h1: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	h2: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	h3: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	h4: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	h5: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	h6: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	p: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	blockquote: { quotes: "none" },
	pre: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	a: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	abbr: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	acronym: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	address: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	big: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	cite: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	code: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	del: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	dfn: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	em: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	img: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	ins: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	kbd: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	q: { quotes: "none" },
	s: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	samp: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	small: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	strike: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	strong: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	sub: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	sup: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	tt: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	var: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	b: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	u: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	i: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	center: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	dl: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	dt: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	dd: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	ol: { listStyle: "none" },
	ul: { listStyle: "none" },
	li: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	fieldset: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	form: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	label: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	legend: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	table: { borderCollapse: "collapse", borderSpacing: "0" },
	caption: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	tbody: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	tfoot: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	thead: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	tr: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	th: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	td: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	article: { display: "block" },
	aside: { display: "block" },
	canvas: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	details: { display: "block" },
	embed: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	figure: { display: "block" },
	figcaption: { display: "block" },
	footer: { display: "block" },
	header: { display: "block" },
	hgroup: { display: "block" },
	menu: { display: "block" },
	nav: { display: "block" },
	output: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	ruby: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	section: { display: "block" },
	summary: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	time: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	mark: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	audio: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	video: { margin: "0", padding: "0", border: "0", fontSize: "100%", font: "inherit", verticalAlign: "baseline" },
	blockquote_before: { content: "none" },
	blockquote_after: { content: "none" },
	q_before: { content: "none" },
	q_after: { content: "none" },
};
